version: '3'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - laravel-network

  mysql:
    image: mysql:latest
    ports:
      - "3302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
